version: "3.9"

services:
  app:
    build: .
    environment:
      - PORT=8081
    expose:
      - "8081"
    tty: true
    stdin_open: true
    volumes:
      - "./:/app"

# リバプロ
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

